spring.config.import: "configserver:"

spring:
  application.name: eureka-server
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
  profiles:
    active: dev

spring.cloud.config.uri: http://configserver:8071
---
spring.config.activate.on-profile: local

spring.cloud.config.uri: http://localhost:8071
